apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-first-service
  description: Practice service for learning Backstage
spec:
  type: service
  lifecycle: experimental
  owner: guests
  dependsOn:
    - component:default/user-service
